# nixpacks.toml

[phases.setup]
# Lista expandida de paquetes del sistema para asegurar la compatibilidad de las librerías de imágenes
aptPkgs = ["build-essential", "libjpeg62-turbo", "libjpeg-turbo-progs"]